# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "pgsql:porkast:1qaz!QAZ@tcp(127.0.0.1:5432)/porkastdb"
  build:
    name: "porkast-crawler"
    arch: "amd64"
    system: "linux"
    path: "./bin"
    packSrc: "resource,manifest"
    # version: "v1.0.0"
    extra: "-trimpath"
