// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"errors"
	"guoshao-fm-crawler/internal/model/entity"
	"guoshao-fm-crawler/internal/service/internal/dao/internal"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// feedChannelDao is the data access object for table feed_channel.
// You can define custom methods on it to extend its functionality as you wish.
type feedChannelDao struct {
	*internal.FeedChannelDao
}

var (
	// FeedChannel is globally public accessible object for table feed_channel operations.
	FeedChannel = feedChannelDao{
		internal.NewFeedChannelDao(),
	}
)

// Fill with you ideas below.
func InsertFeedChannelIfNotExist(ctx context.Context, model entity.FeedChannel) error {
	var (
		err    error
		result gdb.Record
	)
	result, _ = FeedChannel.Ctx(ctx).Where("id=?", model.Id).One()
	if result.IsEmpty() {
		g.Log().Line().Debugf(ctx, "Insert feed channel %s to DB", model.Title)
		_, err = FeedChannel.Ctx(ctx).Insert(model)
	} else {
		return errors.New("The Feed Channel is exist")
	}
	return err
}
