// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"porkast-crawler/internal/model/entity"
	"porkast-crawler/internal/service/internal/dao/internal"
)

// feedChannelUpdateRecordDao is the data access object for table feed_channel_update_record.
// You can define custom methods on it to extend its functionality as you wish.
type feedChannelUpdateRecordDao struct {
	*internal.FeedChannelUpdateRecordDao
}

var (
	// FeedChannelUpdateRecord is globally public accessible object for table feed_channel_update_record operations.
	FeedChannelUpdateRecord = feedChannelUpdateRecordDao{
		internal.NewFeedChannelUpdateRecordDao(),
	}
)

// Fill with you ideas below.
func InsertOrUpdateFeedChannelUpdateRecord(ctx context.Context, data entity.FeedChannelUpdateRecord) (err error) {

	var queryEntity entity.FeedChannelUpdateRecord
	FeedChannelUpdateRecord.Ctx(ctx).Where("channel_id=?", data.ChannelId).Scan(&queryEntity)
	if queryEntity.ChannelId == "" {
        _, err = FeedChannelUpdateRecord.Ctx(ctx).Save(data)
	} else {
        _, err = FeedChannelUpdateRecord.Ctx(ctx).Update(data)
	}

	return
}
